version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/lightsail-docker-node  # Adjusted to typical Ubuntu user
hooks:
  ApplicationStop:
    - location: scripts/stop_docker.sh
      timeout: 30
      runas: root
  BeforeInstall:
      runas: root
    - location: scripts/cleanup.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start_docker.sh
      timeout: 30
      runas: root
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 30
      runas: root

