version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo Installing source dependencies...
      - npm install
  pre_build:
    commands:
      - env
      - which docker
      - docker --version
      - cat /codebuild/output/tmp/script.sh
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 533267141943.dkr.ecr.us-east-1.amazonaws.com)
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t lightsail-docker-node:$CODEBUILD_RESOLVED_SOURCE_VERSION .
  post_build:
    commands:
      - echo Pushing the Docker image to Amazon ECR...
      - docker push lightsail-docker-node:$CODEBUILD_RESOLVED_SOURCE_VERSION

artifacts:
  files:
    - appspec.yml
    - scripts/*
